# Site settings
title: Eric R. Franco
description: Portfolio
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "ericrfranco.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Eric R. Franco
user_description: I am a Game and Simulation Arts and Sciences undergraduate at Rensselaer Polytechnic Institute, and my strengths lie in both coding and creative writing. Below you will find all of the projects that best showcase these skills.
user_title: Game Developer
email: ericrfranco219@gmail.com
twitter_username: "@franc0o__"
github_username:  EricRFranco
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
